apiVersion: v1
kind: Secret
metadata:
  name: {{ include "eche-mesh.fullname" . }}
  labels:
    {{- include "eche-mesh.labels" . | nindent 4 }}
type: Opaque
data:
  formation-secret: {{ .Values.formationSecret | b64enc | quote }}
