{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "eche-mesh.serviceAccountName" . }}
  labels:
    {{- include "eche-mesh.labels" . | nindent 4 }}
{{- end }}
