apiVersion: v1
kind: Service
metadata:
  name: {{ include "eche-mesh.fullname" . }}
  labels:
    {{- include "eche-mesh.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "eche-mesh.selectorLabels" . | nindent 4 }}
  ports:
    - name: broker
      port: {{ .Values.brokerPort }}
      targetPort: broker
      protocol: TCP
    - name: iroh-quic
      port: {{ .Values.irohBindPort }}
      targetPort: iroh-quic
      protocol: UDP
