{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "peat-mesh.serviceAccountName" . }}
  labels:
    {{- include "peat-mesh.labels" . | nindent 4 }}
{{- end }}
